//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Musteriler()
        {
            this.Tbl_Satis = new HashSet<Tbl_Satis>();
        }
    
        public int MUSTERIID { get; set; }
        [Required(ErrorMessage ="Bu Alan boþ geçilemez!")]
        [StringLength(50,ErrorMessage ="Lütfen 50 karakteri geçmeyin!")]
        public string MUSTERIAD { get; set; }
        [Required(ErrorMessage = "Bu Alan boþ geçilemez!")]
        [StringLength(50, ErrorMessage = "Lütfen 50 karakteri geçmeyin!")]
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satis> Tbl_Satis { get; set; }
    }
}
